# Generated by Django 5.0.2 on 2024-06-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='option',
        ),
        migrations.AddField(
            model_name='cours',
            name='option',
            field=models.ManyToManyField(to='grams.filiere'),
        ),
    ]
