# Generated by Django 5.0.2 on 2024-06-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grams', '0002_remove_cours_option_cours_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='prerequis',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
