# Generated by Django 5.0.2 on 2024-06-13 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grams', '0003_alter_cours_prerequis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcours',
            old_name='codeDep',
            new_name='codePar',
        ),
        migrations.AddField(
            model_name='filiere',
            name='parcours',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parcours', to='grams.departement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filiere',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departement', to='grams.departement'),
        ),
    ]
