# Generated by Django 5.0.2 on 2024-06-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='adresse',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='contact',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type_compte',
            field=models.CharField(choices=[("Etudiant à l'EPL", 'Etu'), ("Enseignant à l'EPL", 'Ens'), ("Invite (Etudiant ou Enseignant d'autres facultés, écoles)", 'Inv')], default="Etudiant à l'EPL"),
        ),
    ]
